package db2go2types

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/jackc/pgx/v5"
)

// Generate connects to cfg.DSN, reads cfg.Schema and writes the generated
// package to cfg.OutputDir and the diagram to cfg.DiagramPath.
func Generate(ctx context.Context, cfg Config) error {
	if cfg.DSN == "" {
		return fmt.Errorf("db2go2types: Config.DSN is required")
	}
	conn, err := pgx.Connect(ctx, cfg.DSN)
	if err != nil {
		return fmt.Errorf("db2go2types: connect: %w", err)
	}
	defer conn.Close(context.WithoutCancel(ctx))
	return GenerateFrom(ctx, conn, cfg)
}

// GenerateFrom is [Generate] with an open connection; cfg.DSN is ignored.
func GenerateFrom(ctx context.Context, db Querier, cfg Config) error {
	cfg, err := cfg.withDefaults()
	if err != nil {
		return err
	}
	s, err := Inspect(ctx, db, cfg.Schema)
	if err != nil {
		return err
	}
	cfg.Logger.Info("schema read", "schema", s.Name, "tables", len(s.Tables), "enums", len(s.Enums))

	src, err := Render(s, cfg)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(cfg.OutputDir, 0o755); err != nil {
		return fmt.Errorf("db2go2types: %w", err)
	}
	path := filepath.Join(cfg.OutputDir, ModelsFile)
	if err := writeGenerated(path, src); err != nil {
		return err
	}
	cfg.Logger.Info("written", "file", path)
	if cfg.DiagramPath != "" {
		if err := os.MkdirAll(filepath.Dir(cfg.DiagramPath), 0o755); err != nil {
			return fmt.Errorf("db2go2types: %w", err)
		}
		if err := os.WriteFile(cfg.DiagramPath, Diagram(s), 0o644); err != nil {
			return fmt.Errorf("db2go2types: %w", err)
		}
		cfg.Logger.Info("written", "file", cfg.DiagramPath)
	}
	return nil
}

// generatedMarker starts every file written by Render.
var generatedMarker = []byte("// Code generated by db2go2types. DO NOT EDIT.")

// writeGenerated writes a generated file, refusing to overwrite a file that
// was not generated, so a wrong -out cannot destroy hand-written code.
func writeGenerated(path string, src []byte) error {
	old, err := os.ReadFile(path)
	switch {
	case errors.Is(err, fs.ErrNotExist):
	case err != nil:
		return fmt.Errorf("db2go2types: %w", err)
	case !bytes.HasPrefix(old, generatedMarker):
		return fmt.Errorf("db2go2types: %s exists and was not generated by db2go2types; remove it or choose another output directory", path)
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return fmt.Errorf("db2go2types: %w", err)
	}
	return nil
}
