package db2go2types

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGoName(t *testing.T) {
	for in, want := range map[string]string{
		"id_user": "IdUser", "posts": "Posts", "in-progress": "InProgress", "#A6D2FF": "A6D2FF",
		"2fa_codes": "X2faCodes", "": "X", "__": "X", "é_t": "ÉT",
	} {
		if got := goName(in); got != want {
			t.Errorf("goName(%q) = %q, want %q", in, got, want)
		}
	}
	if got := enumConstName("Color", "#A6D2FF", map[string]string{"#A6D2FF": "blue"}); got != "ColorBlue" {
		t.Errorf("custom enum name = %q", got)
	}
	if got := enumConstName("Mode", "", nil); got != "ModeEmpty" {
		t.Errorf("empty enum value = %q", got)
	}
	for dir, want := range map[string]string{"pkg/db-models": "dbmodels", "pkg/Models": "models", "pkg/2go": "models", "pkg/type": "models"} {
		if got := packageName(dir); got != want {
			t.Errorf("packageName(%q) = %q, want %q", dir, got, want)
		}
	}
}

func TestGoType(t *testing.T) {
	s := &Schema{Enums: []Enum{{Name: "mood", Values: []string{"ok"}}}}
	for _, tc := range []struct {
		col  Column
		want string
	}{
		{Column{Type: "integer"}, "int"},
		{Column{Type: "timestamp with time zone", IsNullable: true}, "*time.Time"},
		{Column{Type: "mood"}, "Mood"},
		{Column{Type: "ARRAY:mood"}, "[]Mood"},
		{Column{Type: "ARRAY:int8"}, "[]int64"},
		{Column{Type: "ARRAY:text", IsNullable: true}, "[]any"},
		{Column{Type: "inet"}, "any"},
		{Column{Type: "jsonb", IsNullable: true}, "*any"},
	} {
		if got := s.goType(tc.col); got != tc.want {
			t.Errorf("goType(%+v) = %s, want %s", tc.col, got, tc.want)
		}
	}
}

func TestRenderEdgeCases(t *testing.T) {
	s := &Schema{
		Name:  "app",
		Enums: []Enum{{Name: "kind", Values: []string{"a-b", "a_b", "a b"}}},
		Tables: []Table{
			{Schema: "app", Name: "user", Columns: []Column{
				{Name: "id", Type: "bigint"},
				{Name: "na`me", Type: "text", IsNullable: true},
				{Name: "kinds", Type: "ARRAY:kind"},
			}},
		},
	}
	src, err := Render(s, Config{Package: "db"})
	if err != nil {
		t.Fatal(err)
	}
	models := string(src)
	for _, want := range []string{
		"// Code generated by db2go2types. DO NOT EDIT.\n\npackage db\n",
		"KindAB  Kind = \"a-b\"", "KindAB2 Kind = \"a_b\"", "KindAB3 Kind = \"a b\"",
		"type User struct {", "NaMe  *string", "Kinds []Kind",
	} {
		if !strings.Contains(models, want) {
			t.Errorf("models.go has no %q:\n%s", want, models)
		}
	}
	if strings.Contains(models, `"time"`) {
		t.Error("models.go imports time without time columns")
	}

	empty, err := Render(&Schema{Name: "empty"}, Config{})
	if err != nil || string(empty) != "// Code generated by db2go2types. DO NOT EDIT.\n\npackage models\n" {
		t.Errorf("empty schema: %q, %v", empty, err)
	}
}

func TestRenderRejects(t *testing.T) {
	for name, tc := range map[string]struct {
		s   *Schema
		cfg Config
	}{
		"package injection": {&Schema{}, Config{Package: "x\nimport \"os\""}},
		"keyword package":   {&Schema{}, Config{Package: "func"}},
		"table and enum": {&Schema{
			Enums:  []Enum{{Name: "status", Values: []string{"a"}}},
			Tables: []Table{{Name: "status"}},
		}, Config{}},
		"two tables": {&Schema{Tables: []Table{{Name: "post_tags"}, {Name: "postTags"}}}, Config{}},
		"two columns": {&Schema{Tables: []Table{{Name: "t", Columns: []Column{
			{Name: "user_id", Type: "int"}, {Name: "userId", Type: "int"},
		}}}}, Config{}},
	} {
		if _, err := Render(tc.s, tc.cfg); err == nil {
			t.Errorf("%s: accepted", name)
		}
	}
}

func TestWriteGenerated(t *testing.T) {
	path := filepath.Join(t.TempDir(), ModelsFile)
	if err := os.WriteFile(path, []byte("package mine\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := writeGenerated(path, []byte("x")); err == nil {
		t.Error("hand-written file overwritten")
	}
	src := append(append([]byte{}, generatedMarker...), "\n\npackage models\n"...)
	if err := os.WriteFile(path, src, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := writeGenerated(path, src); err != nil {
		t.Errorf("generated file not replaced: %v", err)
	}
}

func TestDiagram(t *testing.T) {
	s := &Schema{Tables: []Table{{Name: "posts",
		Columns:     []Column{{Name: "tags", Type: "ARRAY:text", IsNullable: true}},
		ForeignKeys: []ForeignKey{{Table: "posts", Column: "author_id", ForeignTable: "authors"}},
	}}}
	got := string(Diagram(s))
	for _, want := range []string{"class posts {", "text[] tags (nullable)", "posts --> authors : author_id"} {
		if !strings.Contains(got, want) {
			t.Errorf("diagram has no %q:\n%s", want, got)
		}
	}
}

func TestConfig(t *testing.T) {
	if _, err := (Config{}).withDefaults(); err == nil {
		t.Error("empty schema accepted")
	}
	c, err := Config{Schema: "public"}.withDefaults()
	if err != nil || c.OutputDir != DefaultOutputDir || c.Package != "models" || c.Logger == nil {
		t.Errorf("defaults = %+v, %v", c, err)
	}
}

func TestDSNFromEnv(t *testing.T) {
	t.Setenv("DATABASE_URL", "")
	for _, key := range []string{"POSTGRES_HOST", "POSTGRES_PORT", "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DATABASE", "POSTGRES_SSLMODE"} {
		t.Setenv(key, "")
	}
	if _, err := DSNFromEnv(); err == nil || !strings.Contains(err.Error(), "POSTGRES_HOST") {
		t.Errorf("missing variables: %v", err)
	}
	t.Setenv("POSTGRES_HOST", "db")
	t.Setenv("POSTGRES_PORT", "5432")
	t.Setenv("POSTGRES_USER", "app")
	t.Setenv("POSTGRES_PASSWORD", "p@ss/word")
	t.Setenv("POSTGRES_DATABASE", "shop")
	t.Setenv("POSTGRES_SSLMODE", "disable")
	if dsn, err := DSNFromEnv(); err != nil || dsn != "postgres://app:p%40ss%2Fword@db:5432/shop?sslmode=disable" {
		t.Errorf("DSN = %s, %v", dsn, err)
	}
	t.Setenv("DATABASE_URL", "postgres://x")
	if dsn, _ := DSNFromEnv(); dsn != "postgres://x" {
		t.Errorf("DATABASE_URL ignored: %s", dsn)
	}
}
