// Code generated by db2go2types. DO NOT EDIT.

package repository

import "time"

type LabelColor string

const (
	LabelColorBlue  LabelColor = "#A6D2FF"
	LabelColorRed   LabelColor = "#F87659"
	LabelColorGreen LabelColor = "#BCF1A5"
)

type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
)

type Authors struct {
	Id        int    `validate:"required"`
	Name      string `validate:"required"`
	Email     *string
	CreatedAt time.Time `validate:"required"`
}

type PostLikes struct {
	PostId   int `validate:"required"`
	AuthorId int `validate:"required"`
}

type Posts struct {
	Id          int          `validate:"required"`
	AuthorId    int          `validate:"required"`
	Title       string       `validate:"required"`
	Status      PostStatus   `validate:"required"`
	Labels      []LabelColor `validate:"required"`
	Tags        []any
	Order       int   `validate:"required"`
	Views       int64 `validate:"required"`
	Rating      *float64
	Meta        *any
	PublishedAt *time.Time
}

type UpdateAuthorsParams struct {
	Name      string `validate:"required"`
	Email     *string
	CreatedAt time.Time `validate:"required"`
}

type UpdatePostLikesParams struct {
	PostId   int `validate:"required"`
	AuthorId int `validate:"required"`
}

type UpdatePostsParams struct {
	AuthorId    int          `validate:"required"`
	Title       string       `validate:"required"`
	Status      PostStatus   `validate:"required"`
	Labels      []LabelColor `validate:"required"`
	Tags        []any
	Order       int   `validate:"required"`
	Views       int64 `validate:"required"`
	Rating      *float64
	Meta        *any
	PublishedAt *time.Time
}
