// Code generated by db2go2types. DO NOT EDIT.

package repository

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is implemented by *pgx.Conn, *pgxpool.Pool and pgx.Tx.
type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

// AuthorsRepository runs queries on the Authors table.
//
// Methods that take a where clause or a custom query append it to the SQL as is.
// Never build them from user input: use ExecuteQueryAuthors with parameters instead.
type AuthorsRepository interface {
	AddAuthors(ctx context.Context, arg UpdateAuthorsParams, customQuery *string) (Authors, error)
	UpdateAuthors(ctx context.Context, arg UpdateAuthorsParams, where *string) (Authors, error)
	SelectAuthors(ctx context.Context, where *string) ([]Authors, error)
	GetAuthors(ctx context.Context, id int, customQuery *string) (Authors, error)
	DeleteAuthors(ctx context.Context, where string) error
	CountAuthors(ctx context.Context, where *string) (int64, error)
	// ExecuteQueryAuthors runs a parameterized query that returns all columns of the table.
	ExecuteQueryAuthors(ctx context.Context, query string, args ...any) ([]Authors, error)
	// ExecuteQueryRowAuthors runs a parameterized query that returns all columns of one row.
	ExecuteQueryRowAuthors(ctx context.Context, query string, args ...any) (Authors, error)
}

type authorsRepository struct {
	db DBTX
}

// NewAuthorsRepository returns a AuthorsRepository that runs queries on db.
func NewAuthorsRepository(db DBTX) AuthorsRepository {
	return &authorsRepository{db: db}
}

func (q *authorsRepository) scanAuthors(row pgx.Row) (Authors, error) {
	var result Authors
	err := row.Scan(
		&result.Id,
		&result.Name,
		&result.Email,
		&result.CreatedAt,
	)
	return result, err
}

func (q *authorsRepository) collectAuthors(rows pgx.Rows, err error) ([]Authors, error) {
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []Authors
	for rows.Next() {
		result, err := q.scanAuthors(rows)
		if err != nil {
			return nil, err
		}
		results = append(results, result)
	}
	return results, rows.Err()
}

// AddAuthors inserts a row and returns it. customQuery, if not nil, replaces the INSERT
// and gets the same arguments.
func (q *authorsRepository) AddAuthors(ctx context.Context, arg UpdateAuthorsParams, customQuery *string) (Authors, error) {
	query := `INSERT INTO "blog"."authors" ("name", "email", "created_at") VALUES ($1, $2, $3) RETURNING "id", "name", "email", "created_at"`
	if customQuery != nil {
		query = *customQuery
	}
	return q.scanAuthors(q.db.QueryRow(ctx, query,
		arg.Name,
		arg.Email,
		arg.CreatedAt,
	))
}

// UpdateAuthors sets all columns except the primary key in the rows matched by where,
// e.g. "WHERE id = 1", and returns the first updated row.
func (q *authorsRepository) UpdateAuthors(ctx context.Context, arg UpdateAuthorsParams, where *string) (Authors, error) {
	query := `UPDATE "blog"."authors" SET "name" = $1, "email" = $2, "created_at" = $3 `
	if where != nil {
		query += *where
	}
	query += ` RETURNING "id", "name", "email", "created_at"`
	return q.scanAuthors(q.db.QueryRow(ctx, query,
		arg.Name,
		arg.Email,
		arg.CreatedAt,
	))
}

// SelectAuthors returns the rows matched by where, e.g. "WHERE id > 10 ORDER BY id",
// or all rows when where is nil.
func (q *authorsRepository) SelectAuthors(ctx context.Context, where *string) ([]Authors, error) {
	query := `SELECT "id", "name", "email", "created_at" FROM "blog"."authors" `
	if where != nil {
		query += *where
	}
	return q.collectAuthors(q.db.Query(ctx, query))
}

// GetAuthors returns the row with the primary key id. customQuery, if not nil,
// replaces the SELECT and gets no arguments.
func (q *authorsRepository) GetAuthors(ctx context.Context, id int, customQuery *string) (Authors, error) {
	if customQuery != nil {
		return q.scanAuthors(q.db.QueryRow(ctx, *customQuery))
	}
	return q.scanAuthors(q.db.QueryRow(ctx, `SELECT "id", "name", "email", "created_at" FROM "blog"."authors" WHERE "id" = $1`, id))
}

// DeleteAuthors deletes the rows matched by where, e.g. "WHERE id = 1".
// An empty where is an error, so the whole table cannot be deleted by mistake.
func (q *authorsRepository) DeleteAuthors(ctx context.Context, where string) error {
	if where == "" {
		return errors.New("where not provided for delete method")
	}
	_, err := q.db.Exec(ctx, `DELETE FROM "blog"."authors" `+where)
	return err
}

// CountAuthors counts the rows matched by where, or all rows when where is nil.
func (q *authorsRepository) CountAuthors(ctx context.Context, where *string) (int64, error) {
	query := `SELECT COUNT(*) FROM "blog"."authors" `
	if where != nil {
		query += *where
	}
	var count int64
	err := q.db.QueryRow(ctx, query).Scan(&count)
	return count, err
}

func (q *authorsRepository) ExecuteQueryAuthors(ctx context.Context, query string, args ...any) ([]Authors, error) {
	return q.collectAuthors(q.db.Query(ctx, query, args...))
}

func (q *authorsRepository) ExecuteQueryRowAuthors(ctx context.Context, query string, args ...any) (Authors, error) {
	return q.scanAuthors(q.db.QueryRow(ctx, query, args...))
}

// PostLikesRepository runs queries on the PostLikes table.
//
// Methods that take a where clause or a custom query append it to the SQL as is.
// Never build them from user input: use ExecuteQueryPostLikes with parameters instead.
type PostLikesRepository interface {
	AddPostLikes(ctx context.Context, arg UpdatePostLikesParams, customQuery *string) (PostLikes, error)
	UpdatePostLikes(ctx context.Context, arg UpdatePostLikesParams, where *string) (PostLikes, error)
	SelectPostLikes(ctx context.Context, where *string) ([]PostLikes, error)
	GetPostLikes(ctx context.Context, id int, customQuery *string) (PostLikes, error)
	DeletePostLikes(ctx context.Context, where string) error
	CountPostLikes(ctx context.Context, where *string) (int64, error)
	// ExecuteQueryPostLikes runs a parameterized query that returns all columns of the table.
	ExecuteQueryPostLikes(ctx context.Context, query string, args ...any) ([]PostLikes, error)
	// ExecuteQueryRowPostLikes runs a parameterized query that returns all columns of one row.
	ExecuteQueryRowPostLikes(ctx context.Context, query string, args ...any) (PostLikes, error)
}

type postLikesRepository struct {
	db DBTX
}

// NewPostLikesRepository returns a PostLikesRepository that runs queries on db.
func NewPostLikesRepository(db DBTX) PostLikesRepository {
	return &postLikesRepository{db: db}
}

func (q *postLikesRepository) scanPostLikes(row pgx.Row) (PostLikes, error) {
	var result PostLikes
	err := row.Scan(
		&result.PostId,
		&result.AuthorId,
	)
	return result, err
}

func (q *postLikesRepository) collectPostLikes(rows pgx.Rows, err error) ([]PostLikes, error) {
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []PostLikes
	for rows.Next() {
		result, err := q.scanPostLikes(rows)
		if err != nil {
			return nil, err
		}
		results = append(results, result)
	}
	return results, rows.Err()
}

// AddPostLikes inserts a row and returns it. customQuery, if not nil, replaces the INSERT
// and gets the same arguments.
func (q *postLikesRepository) AddPostLikes(ctx context.Context, arg UpdatePostLikesParams, customQuery *string) (PostLikes, error) {
	query := `INSERT INTO "blog"."post_likes" ("post_id", "author_id") VALUES ($1, $2) RETURNING "post_id", "author_id"`
	if customQuery != nil {
		query = *customQuery
	}
	return q.scanPostLikes(q.db.QueryRow(ctx, query,
		arg.PostId,
		arg.AuthorId,
	))
}

// UpdatePostLikes sets all columns except the primary key in the rows matched by where,
// e.g. "WHERE id = 1", and returns the first updated row.
func (q *postLikesRepository) UpdatePostLikes(ctx context.Context, arg UpdatePostLikesParams, where *string) (PostLikes, error) {
	query := `UPDATE "blog"."post_likes" SET "post_id" = $1, "author_id" = $2 `
	if where != nil {
		query += *where
	}
	query += ` RETURNING "post_id", "author_id"`
	return q.scanPostLikes(q.db.QueryRow(ctx, query,
		arg.PostId,
		arg.AuthorId,
	))
}

// SelectPostLikes returns the rows matched by where, e.g. "WHERE id > 10 ORDER BY id",
// or all rows when where is nil.
func (q *postLikesRepository) SelectPostLikes(ctx context.Context, where *string) ([]PostLikes, error) {
	query := `SELECT "post_id", "author_id" FROM "blog"."post_likes" `
	if where != nil {
		query += *where
	}
	return q.collectPostLikes(q.db.Query(ctx, query))
}

// GetPostLikes returns the row with the primary key id. customQuery, if not nil,
// replaces the SELECT and gets no arguments.
func (q *postLikesRepository) GetPostLikes(ctx context.Context, id int, customQuery *string) (PostLikes, error) {
	if customQuery != nil {
		return q.scanPostLikes(q.db.QueryRow(ctx, *customQuery))
	}
	return q.scanPostLikes(q.db.QueryRow(ctx, `SELECT "post_id", "author_id" FROM "blog"."post_likes" WHERE "id" = $1`, id))
}

// DeletePostLikes deletes the rows matched by where, e.g. "WHERE id = 1".
// An empty where is an error, so the whole table cannot be deleted by mistake.
func (q *postLikesRepository) DeletePostLikes(ctx context.Context, where string) error {
	if where == "" {
		return errors.New("where not provided for delete method")
	}
	_, err := q.db.Exec(ctx, `DELETE FROM "blog"."post_likes" `+where)
	return err
}

// CountPostLikes counts the rows matched by where, or all rows when where is nil.
func (q *postLikesRepository) CountPostLikes(ctx context.Context, where *string) (int64, error) {
	query := `SELECT COUNT(*) FROM "blog"."post_likes" `
	if where != nil {
		query += *where
	}
	var count int64
	err := q.db.QueryRow(ctx, query).Scan(&count)
	return count, err
}

func (q *postLikesRepository) ExecuteQueryPostLikes(ctx context.Context, query string, args ...any) ([]PostLikes, error) {
	return q.collectPostLikes(q.db.Query(ctx, query, args...))
}

func (q *postLikesRepository) ExecuteQueryRowPostLikes(ctx context.Context, query string, args ...any) (PostLikes, error) {
	return q.scanPostLikes(q.db.QueryRow(ctx, query, args...))
}

// PostsRepository runs queries on the Posts table.
//
// Methods that take a where clause or a custom query append it to the SQL as is.
// Never build them from user input: use ExecuteQueryPosts with parameters instead.
type PostsRepository interface {
	AddPosts(ctx context.Context, arg UpdatePostsParams, customQuery *string) (Posts, error)
	UpdatePosts(ctx context.Context, arg UpdatePostsParams, where *string) (Posts, error)
	SelectPosts(ctx context.Context, where *string) ([]Posts, error)
	GetPosts(ctx context.Context, id int, customQuery *string) (Posts, error)
	DeletePosts(ctx context.Context, where string) error
	CountPosts(ctx context.Context, where *string) (int64, error)
	// ExecuteQueryPosts runs a parameterized query that returns all columns of the table.
	ExecuteQueryPosts(ctx context.Context, query string, args ...any) ([]Posts, error)
	// ExecuteQueryRowPosts runs a parameterized query that returns all columns of one row.
	ExecuteQueryRowPosts(ctx context.Context, query string, args ...any) (Posts, error)
}

type postsRepository struct {
	db DBTX
}

// NewPostsRepository returns a PostsRepository that runs queries on db.
func NewPostsRepository(db DBTX) PostsRepository {
	return &postsRepository{db: db}
}

func (q *postsRepository) scanPosts(row pgx.Row) (Posts, error) {
	var result Posts
	err := row.Scan(
		&result.Id,
		&result.AuthorId,
		&result.Title,
		&result.Status,
		&result.Labels,
		&result.Tags,
		&result.Order,
		&result.Views,
		&result.Rating,
		&result.Meta,
		&result.PublishedAt,
	)
	return result, err
}

func (q *postsRepository) collectPosts(rows pgx.Rows, err error) ([]Posts, error) {
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []Posts
	for rows.Next() {
		result, err := q.scanPosts(rows)
		if err != nil {
			return nil, err
		}
		results = append(results, result)
	}
	return results, rows.Err()
}

// AddPosts inserts a row and returns it. customQuery, if not nil, replaces the INSERT
// and gets the same arguments.
func (q *postsRepository) AddPosts(ctx context.Context, arg UpdatePostsParams, customQuery *string) (Posts, error) {
	query := `INSERT INTO "blog"."posts" ("author_id", "title", "status", "labels", "tags", "order", "views", "rating", "meta", "published_at") VALUES ($1, $2, $3, $4::text[]::"blog"."label_color"[], $5, $6, $7, $8, $9, $10) RETURNING "id", "author_id", "title", "status", "labels"::text[], "tags", "order", "views", "rating", "meta", "published_at"`
	if customQuery != nil {
		query = *customQuery
	}
	return q.scanPosts(q.db.QueryRow(ctx, query,
		arg.AuthorId,
		arg.Title,
		arg.Status,
		arg.Labels,
		arg.Tags,
		arg.Order,
		arg.Views,
		arg.Rating,
		arg.Meta,
		arg.PublishedAt,
	))
}

// UpdatePosts sets all columns except the primary key in the rows matched by where,
// e.g. "WHERE id = 1", and returns the first updated row.
func (q *postsRepository) UpdatePosts(ctx context.Context, arg UpdatePostsParams, where *string) (Posts, error) {
	query := `UPDATE "blog"."posts" SET "author_id" = $1, "title" = $2, "status" = $3, "labels" = $4::text[]::"blog"."label_color"[], "tags" = $5, "order" = $6, "views" = $7, "rating" = $8, "meta" = $9, "published_at" = $10 `
	if where != nil {
		query += *where
	}
	query += ` RETURNING "id", "author_id", "title", "status", "labels"::text[], "tags", "order", "views", "rating", "meta", "published_at"`
	return q.scanPosts(q.db.QueryRow(ctx, query,
		arg.AuthorId,
		arg.Title,
		arg.Status,
		arg.Labels,
		arg.Tags,
		arg.Order,
		arg.Views,
		arg.Rating,
		arg.Meta,
		arg.PublishedAt,
	))
}

// SelectPosts returns the rows matched by where, e.g. "WHERE id > 10 ORDER BY id",
// or all rows when where is nil.
func (q *postsRepository) SelectPosts(ctx context.Context, where *string) ([]Posts, error) {
	query := `SELECT "id", "author_id", "title", "status", "labels"::text[], "tags", "order", "views", "rating", "meta", "published_at" FROM "blog"."posts" `
	if where != nil {
		query += *where
	}
	return q.collectPosts(q.db.Query(ctx, query))
}

// GetPosts returns the row with the primary key id. customQuery, if not nil,
// replaces the SELECT and gets no arguments.
func (q *postsRepository) GetPosts(ctx context.Context, id int, customQuery *string) (Posts, error) {
	if customQuery != nil {
		return q.scanPosts(q.db.QueryRow(ctx, *customQuery))
	}
	return q.scanPosts(q.db.QueryRow(ctx, `SELECT "id", "author_id", "title", "status", "labels"::text[], "tags", "order", "views", "rating", "meta", "published_at" FROM "blog"."posts" WHERE "id" = $1`, id))
}

// DeletePosts deletes the rows matched by where, e.g. "WHERE id = 1".
// An empty where is an error, so the whole table cannot be deleted by mistake.
func (q *postsRepository) DeletePosts(ctx context.Context, where string) error {
	if where == "" {
		return errors.New("where not provided for delete method")
	}
	_, err := q.db.Exec(ctx, `DELETE FROM "blog"."posts" `+where)
	return err
}

// CountPosts counts the rows matched by where, or all rows when where is nil.
func (q *postsRepository) CountPosts(ctx context.Context, where *string) (int64, error) {
	query := `SELECT COUNT(*) FROM "blog"."posts" `
	if where != nil {
		query += *where
	}
	var count int64
	err := q.db.QueryRow(ctx, query).Scan(&count)
	return count, err
}

func (q *postsRepository) ExecuteQueryPosts(ctx context.Context, query string, args ...any) ([]Posts, error) {
	return q.collectPosts(q.db.Query(ctx, query, args...))
}

func (q *postsRepository) ExecuteQueryRowPosts(ctx context.Context, query string, args ...any) (Posts, error) {
	return q.scanPosts(q.db.QueryRow(ctx, query, args...))
}
